[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["element_miniscope*"]
exclude = ["contrib*", "docs*", "tests*", "notebooks*", "images*"]